version: '3.8'

# ==============================================================================
# Bachelor: Edge AI Kjøretøyidentifikasjon - Komplett Infrastruktur
# Denne stakken kjører på Raspberry Pi 5 (16GB RAM) med 2TB NVMe-lagring.
# ==============================================================================

services:
  # 1. Gateway (Caddy) - Reverse Proxy & HTTPS - trenger dette Cloudflare connection med domene.
  gateway:
    image: caddy:latest
    container_name: gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${STORAGE_BASE}/gateway/Caddyfile:/etc/caddy/Caddyfile
      - ${STORAGE_BASE}/gateway/data:/data
      - ${STORAGE_BASE}/gateway/config:/config

  # 2. MQTT (Mosquitto) - Broker for Edge AI-data (ESP32-CAM)
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ${STORAGE_BASE}/mqtt/config:/mosquitto/config
      - ${STORAGE_BASE}/mqtt/data:/mosquitto/data
      - ${STORAGE_BASE}/mqtt/log:/mosquitto/log

  # 3. Database (InfluxDB) - Historisk lagring av kjøretøydata
  db:
    image: influxdb:2
    container_name: db
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ${STORAGE_BASE}/db:/var/lib/influxdb2
      - ${STORAGE_BASE}/db_config:/etc/influxdb2 # Mister ikke volum og gjenbruker samme volum
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=genetiicz
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PW}
      - DOCKER_INFLUXDB_INIT_ORG=bachelor
      - DOCKER_INFLUXDB_INIT_BUCKET=bil_data

  # 4. Cache (Redis) - Lynrask mellomlagring av API-svar fra Vegvesenet
  cache:
    image: redis:latest
    container_name: cache
    restart: always
    command: redis-server --appendonly yes #Lagrer data permanent, slik de ikke hviler bare på RAM.
    ports:
      - "6379:6379"
    volumes:
      - ${STORAGE_BASE}/cache:/data

  # 5. Logic (Node-RED) - Systemets hjerne og API-integrasjon
  logic:
    image: nodered/node-red:latest
    container_name: logic
    restart: always
    user: "1000:1000"
    ports:
      - "1880:1880"
    volumes:
      - ${STORAGE_BASE}/logic:/data #Dette er logikken til Node - Red, her ligger flows.json
      - ${STORAGE_BASE}/bilder:/bilder #Dette er data(bilder) av skilt og bil!
    environment:
      - TZ=Europe/Oslo
      - SVV_API_KEY=${SVV_API_KEY}  #Crucial
      #The variable name must be SVV_API_KEY so that the api works, and it fetch the key from .env

  image-processor:
    build: 
      context: .. #Vi er i rot mappen.
      dockerfile: Docker/Dockerfile #Docker file ligger her nå, det er derfor build failet nå fordi den har blitt flyttet på.
    container_name: image_processor
    restart: always
    ports:
      - "5000:5000"
    volumes:
      # Nå ser begge containerne samme mappe via /bilder
      - ${STORAGE_BASE}/bilder:/bilder 
      # Dette er her vi mapper den nye ai - modellen vi har trent, slik at den kan brukes i image-processor containeren.
      - ${STORAGE_BASE}/modeller:/app/modeller
    environment:
      - TZ=Europe/Oslo
      # .env variabler for rtsp - stream.
      - RTSP_PORT=${RTSP_PORT}
      - RTSP_STREAM_URL=${RTSP_STREAM_URL}